# Generated by Django 4.0.4 on 2022-07-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Members',
        ),
    ]
