name : Bevics Test

on:
  push:
     branches:
        - main

  pull_request:
    branches:
        - main
  
  # on:
  #   schecule
  #   -cron: '*/15 ***

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run:
        python - pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install -U pip
        pip install -upgrade setuptools
        pip install ez_setup
    - name: Lint with flake8
      run:
        pip install flake8
        flake8
    - name: Coverage report
      run:
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Bevics Test
      run:
        python manage.py test



