name : Bevics Test

on:
  push:
     branches:
        - main

  pull_request:
    branches:
        - main
  
  # on:
  #   schecule
  #   -cron: '*/15 ***

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install dependencies
      run:
        python - pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Lint with flake8
      run:
        pip install flake8
        flake8
    - name: Bevics Test
      run:
        python manage.py test



